# Melanoma Detection Pipeline Configuration

processing:
  input_path: "./melanoma_cancer_dataset"
  output_path: "./processed_output"
  target_size: [224, 224]
  hair_kernel_size: [17, 17]
  hair_threshold: 10
  inpaint_radius: 1
  batch_size: 32
  num_workers: 4
  enable_gpu: false

filters:
  kernel_size: 5
  gaussian_sigma: 0.0
  bilateral_d: 9
  bilateral_sigma_color: 75.0
  bilateral_sigma_space: 75.0
  wavelet_type: 'haar'
  wavelet_levels: 1
  fourier_mask_size: 30

logging_level: 'INFO'